### ISSUE TITLE
Notes on HTML

### ISSUE THREAD

**Issue by SidTheEngineer** [akkly/prj-rev-bwfs-dasmoto#1]
Your HTML looks good overall. You've used elements appropriately and they are all in the right place. There are a couple of minor areas for improvement I've highlighted below:

**Small indentation changes**

Within the `<div>`'s, we indent the `<img>` and `<p>` tags even though they are not contained within any other elements (such as `<h2>` or `<h3>`). We can keep these elements on the same level as the `<h2>` and `<h3>`.

**Using the "&" symbol**

In HTML, the "&" symbol is a reserved symbol, meaning that it is used as a part of the HTML syntax. To properly use the ampersand without any issue, we need to use `&amp;` which signifies that we'd like to use the "&" symbol.

**Comment by akkly4u** [comment]
Thank You @SidTheEngineer for the detailed review. Appreciate it. 

Good to know about the Ampersand, earlier always wondered in codes where did these come from.
